[package]
name = "hexchat-plugin"
version = "0.2.11"
authors = ["SoniEx2 <endermoneymod@gmail.com>"]
description = "Lets you write HexChat plugins in Rust"
license = "AGPL-3.0+"
repository = "https://cybre.tech/SoniEx2/rust.hexchat.hexchat-plugin/"

[dependencies]
libc = "0.2"
